# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yc5qM-c-CKiHi7CugXkrXQXr1g-MPP6b
"""

from flask import Flask, request, jsonify, render_template
import MeCab
import json

app = Flask(__name__)

# MeCab初期化
tagger = MeCab.Tagger("-d/var/lib/mecab/dic/debian -r/usr/bin/mecab -Owakati")

# スコア辞書の読み込み
with open("ero_score_dict.json", encoding="utf-8") as f:
    score_dict = json.load(f)

# スコア計算
def classify_ero(text, score_dict):
    words = tagger.parse(text).strip().split()
    return sum(score_dict.get(w, 0) for w in words)

# HTMLページ表示
@app.route('/')
def index():
    return render_template('index.html')

# スコアAPI
@app.route('/score', methods=['POST'])
def score():
    data = request.get_json()
    text = data.get('text', '')
    score = classify_ero(text, score_dict)
    return jsonify({'score': score})

if __name__ == '__main__':
    app.run(debug=True)